# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GreenThumb' do
  use_frameworks!

  pod 'Kingfisher', '~> 4.0'

  target 'GreenThumbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GreenThumbUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
